let arr_jokes = [
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I'm reading a book about anti-gravity. It’s impossible to put down!",
    "What do you call fake spaghetti? An impasta!",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I would tell you a construction pun, but I’m still working on it.",
    "Why don't eggs tell jokes? They’d crack each other up.",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "Knock knock.<br>Who's there?<br>Interrupting.<br> Interrupting who?<br> I was going to tell you a joke.<br>",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why did the math book look sad? Because it had too many problems.",
    "Knock knock.<br>Who's there?<br>Lettuce.<br> Lettuce who?<br> Lettuce go out to dinner.<br>",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Knock knock.<br>Who's there?<br>Can.<br> Can who?<br> Can you hear me?<br>",
    "What did one wall say to the other? I’ll meet you at the corner.",
    "Why couldn’t the bicycle stand up by itself? It was two-tired.",
    "Knock knock.<br>Who's there?<br>Noah.<br> Noah who?<br> Noah body but me.<br>",
    "I told a joke about a roof once, it went over everyone’s head.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I’m on a seafood diet. I see food and I eat it.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "I used to play piano by ear, but now I use my hands.",
    "Knock knock.<br>Who's there?<br>Two.<br> Two who?<br> To who it may concern.<br>",
    "How does a penguin build its house? Igloos it together.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
    "Knock knock.<br>Who's there?<br>A little.<br> A little who?<br> A little late for a joke.<br>",
    "Why was the stadium so hot? Because all the fans left.",
    "I couldn’t figure out why the baseball kept getting bigger. Then it hit me.",
    "Knock knock.<br>Who's there?<br>Adam.<br> Adam who?<br> Adam apple.<br>",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Knock knock.<br>Who's there?<br>Harry.<br> Harry who?<br> Harry up, I'm cold.<br>",
    "Knock knock.<br>Who's there?<br>Europe.<br> Europe who?<br> You rope me in every time.<br>",
    "What’s brown and sticky? A stick.",
    "I used to have a job at a calendar factory, but I got fired because I took a couple of days off.",
    "Why did the coffee file a police report? It got mugged.",
    "Knock knock.<br>Who's there?<br>Cider.<br> Cider who?<br> Cider you later, alligator.<br>",
    "Knock knock.<br>Who's there?<br>I'm.<br> I'm who?<br> I'm sorry, I didn't mean to interrupt.<br>",
    "What’s Forrest Gump’s password? 1forest1.",
    "How do you organize a space party? You planet.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "I was wondering why the frisbee kept getting bigger, then it hit me.",
    "I told my computer I needed a break, and now it won't stop sending me Kit-Kats.",
    "Knock knock.<br>Who's there?<br>Knock knock.<br> Who's there?<br> Knock knock.<br>",
    "Knock knock.<br>Who's there?<br>A door.<br> A door who?<br> A doorable you.<br>",
    "What do you get when you cross a snowman and a vampire? Frostbite.",
    "Why did the picture go to jail? Because it was framed.",
    "Why are frogs so happy? They eat whatever bugs them!",
    "What do you call a belt made of watches? A waist of time.",
    "Knock knock.<br>Who's there?<br>A book.<br> A book who?<br> A book you can't put down.<br>",
    "Knock knock.<br>Who's there?<br>A joke.<br> A joke who?<br> A joke that I'm going to tell you right now: Why did the chicken cross the road?<br> To get to the other side.<br>",
    "I told my wife she should embrace her mistakes. She gave me a hug.",
    "Why don’t seagulls fly over the bay? Because then they’d be bagels.",
    "What did the buffalo say to his son when he dropped him off at school? Bison.",
    "What’s the best thing about Switzerland? I don’t know, but the flag is a big plus.",
    "What do you call a fake noodle? An impasta.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "I would tell you a joke about an elevator, but it’s an uplifting experience.",
    "How do you make holy water? You boil the hell out of it.",
    "Knock knock.<br>Who's there?<br>A police officer.<br> A police officer who?<br> A police officer who says, 'Have you seen my dog?'<br>",
    "Knock knock.<br>Who's there?<br>A doctor.<br> A doctor who?<br> A doctor who says, 'I'm sorry, but you have a terminal illness.'<br>",
    "Why do bananas never get lonely? Because they hang out in bunches.",
    "Why did the bicycle fall over? It was two-tired.",
    "How do trees get online? They log in.",
    "What do you call cheese that isn’t yours? Nacho cheese.",
    "Why did the mushroom go to the party alone? Because he’s a fungi.",
    "Knock knock.<br>Who's there?<br>A lawyer.<br> A lawyer who?<br> A lawyer who says, 'I'll need a retainer fee.'<br>",
    "Knock knock.<br>Who's there?<br>A teacher.<br> A teacher who?<br> A teacher who says, 'I'm going to have to give you detention.'<br>",
    "How do you catch a squirrel? Climb a tree and act like a nut.",
    "Why did the golfer bring an extra pair of pants? In case he got a hole in one.",
    "Why don’t you ever see elephants hiding in trees? Because they’re so good at it.",
    "What’s brown and sticky? A stick.",
    "I used to be addicted to the hokey pokey, but then I turned myself around.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Knock knock.<br>Who's there?<br>A boss.<br> A boss who?<br> A boss who says, 'You're fired.'<br>",
    "Why don’t teddy bears ever eat? They’re always stuffed.",
    "I used to have a fear of hurdles, but I got over it.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why did the cookie go to the doctor? Because it felt crummy.",
    "Knock knock.<br>Who's there?<br>A ghost.<br> A ghost who?<br> A ghost who says, 'Boo!' and then disappears.<br>",
    "How do you make a tissue dance? You put a little boogie in it.",
    "Why don’t skeletons ever use cell phones? They don’t have the guts.",
    "What’s black, white, and read all over? A newspaper.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "Knock knock.<br>Who's there?<br>A robot.<br> A robot who?<br> A robot who says, 'Beep boop, I'm a robot.'<br>",
    "What kind of dog does a magician have? A Labracadabrador.",
    "Why did the math book look sad? It had too many problems.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why did the banana go to the doctor? It wasn’t peeling well.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "Knock knock.<br>Who's there?<br>A ninja.<br> A ninja who?<br> A ninja who says, 'Shhh, I'm sneaking up on you.'<br>",
    "Why don’t vampires attack Taylor Swift? Because she has bad blood.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why don’t some couples go to the gym? Because some relationships don’t work out.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "How do you organize a space party? You planet.",
    "Why don’t oysters donate to charity? Because they’re shellfish.",
    "What do you call an alligator in a vest? An investigator.",
    "I couldn’t figure out why the baseball kept getting bigger. Then it hit me.",
    "Why don’t crabs give to charity? Because they’re shellfish.",
    "What did one hat say to the other? Stay here, I’m going on ahead!",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake.",
    "Why can’t your nose be 12 inches long? Because then it would be a foot!",
    "Knock knock.<br>Who's there?<br>A pirate.<br> A pirate who?<br> A pirate who says, 'Ahoy, matey!'",
    "Knock knock.<br>Who's there?<br>A lawyer.<br> A lawyer who?<br> A lawyer who says, 'I'll need a retainer fee.'<br>",
    "I told a chemistry joke once… There was no reaction.",
    "What did the big flower say to the little flower? Hi, bud!",
    "Why do birds fly south in the winter? It’s faster than walking.",
    "Why don’t we ever tell secrets on a farm? Because the potatoes have eyes and the corn has ears.",
    "What did the fish say when it hit the wall? Dam!",
    "Why did the snowman call his dog Frost? Because he was a cool dog.",
    "Why don’t some fish play basketball? Because they’re afraid of the net.",
    "What’s a frog’s favorite drink? Croak-a-cola.",
    "Why do bees have sticky hair? Because they use honeycombs.",
    "Why don’t graveyards ever get overcrowded? People are dying to get in.",
    "My wife told me to stop impersonating a flamingo. I had to put my foot down.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Dark humor is like food, not everyone gets it.",
    "Why don't orphans play baseball? They don't know where home is.",
    "My grandfather has the heart of a lion and a lifetime ban from the zoo.",
    "Why did the scarecrow win an award? Because he was outstanding in his field. The others died.",
    "The cemetery is a popular place. People are just dying to get in.",
    "I have a stepladder because my real ladder left when I was a kid.",
    "Why don't skeletons fight each other? They don’t have the guts.",
    "Why don’t cannibals eat clowns? Because they taste funny.",
    "I threw a boomerang a few years ago. Now I live in constant fear.",
    "I wasn’t originally going to get a brain transplant, but then I changed my mind.",
    "What’s red and bad for your teeth? A brick.",
    "I told my wife she should embrace her mistakes… so she hugged me.",
    "My parents raised me as an only child, which really annoyed my younger brother.",
    "Why don’t we ever see elephants hiding in trees? Because they’re really good at it.",
    "I have an inferiority complex, but it’s not a very good one.",
    "The early bird might get the worm, but the second mouse gets the cheese.",
    "I used to think I was indecisive. Now I’m not so sure.",
    "I’m not saying I hate you, but I’d unplug your life support to charge my phone.",
    "I told my doctor I broke my arm in two places. He told me to stop going to those places.",
    "My wife asked me to take out the trash. I told her, 'You cooked, you take it out.'",
    "Knock knock.<br>Who's there?<br>A teacher.<br> A teacher who?<br> A teacher who says, 'I'm going to have to give you detention.'<br>",
    "Knock knock.<br>Who's there?<br>A boss.<br> A boss who?<br> A boss who says, 'You're fired.'<br>",
    "What's the difference between a snowman and a snowwoman? Snowballs.",
    "I have a lot of jokes about unemployed people, but none of them work.",
    "What’s worse than finding a worm in your apple? Finding half a worm.",
    "Why don’t blind people skydive? It scares the hell out of their dogs.",
    "I asked my dog what’s two minus two. He said nothing.",
    "I hate Russian dolls. They’re so full of themselves.",
    "Knock knock.<br>Who's there?<br>A ghost.<br> A ghost who?<br> A ghost who says, 'Boo!' and then disappears.<br>",
    "What did the pirate say when he turned 80? Aye matey.",
    "People used to laugh at me when I said I wanted to be a comedian. Well, no one’s laughing now.",
    "Why do cows wear bells? Because their horns don’t work.",
    "I don’t suffer from insanity—I enjoy every minute of it.",
    "What’s orange and sounds like a parrot? A carrot.",
    "Knock knock.<br>Who's there?<br>A robot.<br> A robot who?<br> A robot who says, 'Beep boop, I'm a robot.'<br>",
    "Parallel lines have so much in common. It’s a shame they’ll never meet.",
    "I used to have a job as a professional cricket player, but I got caught out.",
    "How do you surprise a blind man? Leave the plunger in the toilet.",
    "Why don't orphans watch horror movies? Because they can’t scream for their mom.",
    "My wife left me because of my obsession with horror movies. It followed me home.",
    "Why don’t sharks eat clowns? They taste funny.",
    "I bought my friend an elephant for his room. He said, 'Thanks.' I said, 'Don’t mention it.'",
    "I’m on a whiskey diet. I’ve lost three days already.",
    "I told my wife she was driving me crazy. She said, 'You’re lucky I’m not charging.'",
    "If at first you don’t succeed, skydiving is not for you.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "I’m reading a book about anti-gravity. It’s impossible to put down.",
    "My friend got crushed by a pile of books, but he’s only got his shelf to blame.",
    "Knock knock.<br>Who's there?<br>A ninja.<br> A ninja who?<br> A ninja who says, 'Shhh, I'm sneaking up on you.'<br>",
    "Don’t you hate it when someone answers their own questions? I do.",
    "I asked a Frenchman if he played video games. He said Wii.",
    "I’d like to give a big shout-out to all the sidewalks for keeping me off the streets.",
    "My therapist says I have a preoccupation with vengeance. We’ll see about that.",
    "I broke my finger last week. On the other hand, I’m okay.",
    "What do you call a bear with no teeth? A gummy bear.",
    "Why don’t vampires attack Taylor Swift? Because she has bad blood.",
    "I’d tell you a chemistry joke, but I know I wouldn’t get a reaction.",
    "Why can’t you give Elsa a balloon? Because she’ll let it go.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why don't graveyards have Wi-Fi? Because people are already dying to connect.",
    "What's the hardest part about a vegetable to eat? The wheelchair.",
    "Knock knock.<br>Who's there?<br>A pirate.<br> A pirate who?<br> A pirate who says, 'Ahoy, matey!'",
    "Knock, knock.<br>Who's there?<br>Lettuce.<br>Lettuce who?<br>Lettuce in, it's freezing out here!",
    "Knock, knock.<br>Who's there?<br>Boo.<br>Boo who?<br>Don't cry, it's just a joke!",
    "Knock, knock.<br>Who's there?<br>Atch.<br>Atch who?<br>Bless you!",
    "Knock, knock.<br>Who's there?<br>Orange.<br>Orange who?<br>Orange you going to answer the door?",
    "Knock, knock.<br>Who's there?<br>Nobel.<br>Nobel who?<br>No bell, that's why I knocked!",
    "Knock, knock.<br>Who's there?<br>Tank.<br>Tank who?<br>You're welcome!",
    "Knock, knock.<br>Who's there?<br>Dishes.<br>Dishes who?<br>Dishes the police, open up!",
    "Knock, knock.<br>Who's there?<br>Howard.<br>Howard who?<br>Howard you like to be knocked on the door?",
    "Knock, knock.<br>Who's there?<br>Doughnut.<br>Doughnut who?<br>Doughnut forget to say 'who's there?'",
    "What do you call a factory that makes good products?<br>A satisfactory."
  ];

document.getElementById('joke').innerHTML = "Want to hear a joke? Click the button then."

const randomIndex=()=>{
    return Math.floor(Math.random()*191)
}

const generateJoke=()=>{
    let index = randomIndex();
    document.getElementById('joke').innerHTML = arr_jokes[index]
}